# Generated by Django 3.0.3 on 2020-03-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_specificplanlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='book_score',
            field=models.SmallIntegerField(null=True, verbose_name='いいね数'),
        ),
        migrations.AddField(
            model_name='plan',
            name='model_score',
            field=models.SmallIntegerField(null=True, verbose_name='引用数'),
        ),
    ]
