# Generated by Django 3.0.3 on 2020-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200318_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='book_score',
            field=models.SmallIntegerField(default=0, verbose_name='いいね数'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='model_score',
            field=models.SmallIntegerField(default=0, verbose_name='引用数'),
        ),
    ]
