# Generated by Django 2.2.5 on 2020-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200318_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datetime',
        ),
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(null=True, verbose_name='終了日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(null=True, verbose_name='開始日時'),
        ),
    ]
